[project]
name = "ai-lab-project-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=1.2.0",
    "gtts>=2.5.4",
    "pillow>=12.2.0",
    "pyaudio>=0.2.14",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "python-pptx>=1.0.2",
    "speechrecognition>=3.16.0",
    "streamlit>=1.56.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.6.2",
]
